#!/bin/bash

#initial File

#reset environment
sudo rm /opt/cookpombo/cookpombo-init;
sudo rm -Rf /opt/cookpombo;


#create dirs
sudo mkdir /opt/cookpombo;
sudo mkdir /opt/cookpombo/projeto;
sudo chmod 777 /opt/cookpombowww/projeto;



#run commands
cd /opt/cookpombo/projeto; 
sudo wget https://raw.githubusercontent.com/slackwarecps/cookpombo/master/cookpombo-init --no-check-certificate;
sudo chmod 777 /opt/cookpombo/cookpombo-init;
sudo /opt/cookpombo/projeto/cookpombo-init $1 
